// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unlgkmkkaoqghadfjlim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVubGdrbWtrYW9xZ2hhZGZqbGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTQxNzksImV4cCI6MjA1Nzg5MDE3OX0.K32-Lp99iUbFGjOic3NzDmIi_2nscciqOcbZ149Zi34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);